// tools/plugin-devtool/examples/demo-vue/src/view/index.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { createPluginApi } from '@modudesk/plugin-sdk';
import './style.css';

const result = ref('ready');

onMounted(async () => {
  const api = await createPluginApi();
  const value = await api.get('commands').execute('external.demo-vue.ping');
  result.value = String(value);
});
</script>

<template>
  <div class="demo-view-root">
    <h2>Demo View</h2>
    <p>Command Result: {{ result }}</p>
  </div>
</template>

// tools/plugin-devtool/my_plugin/src/view/index.tsx
import React, { useEffect, useState } from 'react';
import { createPluginApi } from '@modudesk-sdk/index';
import './style.css';

export default function PluginView() {
  const [result, setResult] = useState('ready');

  useEffect(() => {
    void (async () => {
      const api = await createPluginApi();
      const value = await api.get('commands').execute('my.plugin.ping');
      setResult(String(value));
    })();
  }, []);

  return (
    <div className="demo-view-root">
      <h2>Demo View</h2>
      <p>Command Result: {result}</p>
    </div>
  );
}
